# Generated by Django 5.1.6 on 2025-03-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
